# Druid 配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 配置
    url: jdbc:mysql://localhost:3306/exclusive_plug?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&verifyServerCertificate=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  session:
    # Redis 配置
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 300
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 5000
    store-type: redis

  application:
    name: admin-server
  security:
    user:
      name: user
      password: admin
server:
  port: 11122
management:
  endpoints:
    web:
      exposure:
        include: "*"

